apiVersion: v1
kind: Service
metadata:
  name: mysvc-app
spec:
  type: NodePort
  selector:
    name: myapp-pod
  ports:
  - port: 8900 # Service IP Port
    targetPort: 80 # Container Port
    name: grpc
  
